### ISSUE TITLE
sweet.js not able to compile a .sjs with cspjs macro

### ISSUE THREAD

**Issue by mseshachalam** [srikumarks/cspjs#3]
//compare.sjs has just this
```
task greet(name) {
   console.log(name);
   return 42;
}
```

sjs -m cspjs compare.sjs > compare.js throws an error.

```
/home/seshachalam/.nvm/versions/node/v0.12.9/lib/node_modules/sweet.js/node_modules/babel-core/lib/transformation/file/index.js:591
      throw err;
            ^
SyntaxError: compare.sjs: 'return' outside of function (5:2)
  3 | {
  4 |   console.log("message");
> 5 |   return 42;
    |   ^
  6 | }
  7 | 
    at Parser.pp.raise (/home/seshachalam/.nvm/versions/node/v0.12.9/lib/node_modules/sweet.js/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.parseReturnStatement (/home/seshachalam/.nvm/versions/node/v0.12.9/lib/node_modules/sweet.js/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:321:10)
    at Parser.pp.parseStatement (/home/seshachalam/.nvm/versions/node/v0.12.9/lib/node_modules/sweet.js/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:107:19)
    at Parser.pp.parseBlockBody (/home/seshachalam/.nvm/versions/node/v0.12.9/lib/node_modules/sweet.js/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:529:21)
    at Parser.pp.parseBlock (/home/seshachalam/.nvm/versions/node/v0.12.9/lib/node_modules/sweet.js/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:510:8)
    at Parser.pp.parseStatement (/home/seshachalam/.nvm/versions/node/v0.12.9/lib/node_modules/sweet.js/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:127:19)
    at Parser.pp.parseBlockBody (/home/seshachalam/.nvm/versions/node/v0.12.9/lib/node_modules/sweet.js/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:529:21)
    at Parser.pp.parseTopLevel (/home/seshachalam/.nvm/versions/node/v0.12.9/lib/node_modules/sweet.js/node_modules/babel-core/node_modules/babylon/lib/parser/statement.js:36:8)
    at Parser.parse (/home/seshachalam/.nvm/versions/node/v0.12.9/lib/node_modules/sweet.js/node_modules/babel-core/node_modules/babylon/lib/parser/index.js:129:19)
    at parse (/home/seshachalam/.nvm/versions/node/v0.12.9/lib/node_modules/sweet.js/node_modules/babel-core/node_modules/babylon/lib/index.js:47:47)
```

node -v
v0.12.9

npm -v
2.14.9

lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

I tried this with node versions 4.44 and 5.6

**Comment by Checksum** [comment]
Not sure what version of Sweet.js you are running, but cspjs doesn't work with v1, mainly because of a new syntax for macros. It should work with 0.7.8 though.
